Style mobile menu
kiboma2021/Ben_Portfolio pull request #10
Opened 2022-05-10 21:46 UTC by kiboma2021

Style mobile menu with DOM Javascript

2022-05-10 23:17 UTC, gtekle requested changes
Hi @kiboma2021 :wave: , 

## You have done a great job implementing the mobile menu! :clap: :clap: :clap: 

There are some issues that you still need to work on to go to the next project but you are almost there!
![this-close](https://user-images.githubusercontent.com/44057863/167739778-eb5ffbbd-a62a-44eb-9e54-aac45408c759.gif)


## Highlights
:heavy_check_mark: Professional Readme :100: 
:heavy_check_mark: Meaningful commit messages
:heavy_check_mark: Good use of Github flow

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please check the inline comments below

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-10 23:17 UTC, gtekle commented on index.html
> +          <span class="bar"> </span>
- [ ] Kindly remove the white gap at the top when mobile menu is open.
- [ ] Kindly add some space at the top for the menu close button as in the Figma design
#### Design
![mobile-menu-top-figma](https://user-images.githubusercontent.com/44057863/167738782-4d9fd7bd-7b37-424c-bce6-7ea6664b7d18.png)
#### Impl
![mobile-menu-top-white-strip](https://user-images.githubusercontent.com/44057863/167738688-11aeb22c-1976-44cf-a920-5b8a748d26d5.png)

2022-05-10 23:17 UTC, gtekle commented on index.html
> +          <div class="intro2 col-12">
- [ Optional ] The headline section is skewed on mobile version. I believe it is due to the desktop image used for mobile. Kindly rectify for better look and feel of your portfolio.
#### Impl
![mobile-headline-section](https://user-images.githubusercontent.com/44057863/167738978-de4356c7-448d-4693-bb7b-f380f2fc1b3b.png)
#### Design
![mobile-headline-section-figma](https://user-images.githubusercontent.com/44057863/167739185-324c8dd5-1dcd-4f9a-963a-fde381764c34.png)

2022-05-10 23:17 UTC, gtekle commented on index.html
> +        <div class="contact-item-2">
- [ Optional ] The contact section is skewed in mobile version and I believe it is due to the background image for desktop used here for mobile as well. Can we rectify this?
#### Design
![mobile-contact-page-figma](https://user-images.githubusercontent.com/44057863/167739426-87fe8e57-108a-467c-a445-f6f1b0467355.png)
#### Imp
![mobile-contact-page](https://user-images.githubusercontent.com/44057863/167739456-1663682a-08db-474c-a1dd-fba9daeb6e42.png)
l

2022-05-10 23:17 UTC, gtekle commented on index.html
>    <body>
- [ Optional ] The is scroll effect while the mobile menu is open. what do you think stopping scroll effect better look and feel? Take a look at this snapshot taken after a bit of down scroll.
![mobile-body-scroll-on-open-menu](https://user-images.githubusercontent.com/44057863/167739601-6a90ad8c-9002-4f06-82bd-d0dc687eedc8.png)

2022-05-11 11:11 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi Team,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-11 14:29 UTC, closed without merging