Add First Page of my Portfolio
kiboma2021/Ben_Portfolio pull request #2
Opened 2022-04-22 19:12 UTC by kiboma2021

This is my first page of my portfolio as a software engineer

2022-04-22 21:22 UTC, koomekevo requested changes
Hi @kiboma2021, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Your README is descriptive.
:heavy_check_mark: Your project has no linter errors.

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly adhere to the design of the Figma template as shown in the below screenshot.

![bencorrectdesign](https://user-images.githubusercontent.com/87413774/164795807-5301313c-1840-44fb-8eb1-77ccd1c38b33.png)

- [ ] Below is a screenshot of your current design. 

![benwrongdesign](https://user-images.githubusercontent.com/87413774/164796105-13b65dae-4797-4982-9715-8130fd062575.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 23:55 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️

![](https://media.giphy.com/media/cE02lboc8JPO/giphy.gif)
@kiboma2021  ✋🏼 
#### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
___
### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏

![almost](https://media.giphy.com/media/oHwvp6bEuiog0bxg2P/giphy.gif)

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-04-22 23:55 UTC, ahmetbozaci commented on README.md
> +This project is [MIT](./MIT.md) licensed.
### OPTIONAL
_I write it as an optional but this is a requirement that is not mentioned in the first review. Please fix it._

- [ ] Please fix the broken link in the license.

2022-04-22 23:55 UTC, ahmetbozaci commented on index.html
> +        </nav>
### OPTIONAL
_I write it as an optional but this is a requirement that is not mentioned in the first review. Please fix it._


- [ ] This part should be wrapped by a header tag. Please fix it. 

- [ ] Only the navbar icon should be wrapped by the nav tag. You should move the tag outside the nav tag.

2022-04-22 23:55 UTC, ahmetbozaci commented on index.html
> +      <main>
### OPTIONAL
_I write it as an optional but this is a requirement that is not mentioned in the first review. Please fix it._


- [ ] You shouldn't wrap all body with div and main tag. Please delete the main and div tags.

2022-04-22 23:55 UTC, ahmetbozaci commented on index.html
> +        </ul>
### Requirement
- [ ] Nice to fix the design.  You should add a background image like in the design.
- [ ] To stick to the design you should change the text color, and font size. 

### ORIGINAL
![image](https://user-images.githubusercontent.com/38635158/164824038-75b5451e-0578-4e5c-80b8-75146ea60d4f.png)
____

### YOUR DESIGN
![image](https://user-images.githubusercontent.com/38635158/164822904-65b31b56-3360-40c6-90b0-3752ab3afaa0.png)



____

### OPTIONAL
_I write it as an optional but this is a requirement that is not mentioned in the first review. Please fix it._


- [ ] This part should be wrapped by a section tag. Please fix it.

2022-04-23 11:11 UTC, DeliceLydia approved these changes
## Hi @kiboma2021, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

## Optional
- [ ] I suggest that you read about [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp) to understand better how to structure your HTML page



### Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 11:11 UTC, DeliceLydia commented on README.md
> +[Live Demo Link](https://ben-microverse-project.com)
## Optional
- [ ] I suggest that you fix your demo link

2022-04-23 14:29 UTC, merged